rules: []
rulesConfigs: []
hooks: []
pages: 
  - name: guardian_multifactor
    enabled: true
    html: ./tenants/tenant2/pages/guardian_multifactor.html
  - name: login
    enabled: true
    html: ./tenants/tenant2/Views/en/default_signup_signin.html
  - name: password_reset
    enabled: true
    html: ./tenants/tenant2/pages/password_reset.html
resourceServers: []
clients:
  - name: Default App
    callbacks: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
  - name: DeployCLI
    app_type: non_interactive
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    enabled_clients:
      - Default App
      - DeployCLI
      - SampleApp
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      passwordPolicy: good
      strategy_version: 2
      brute_force_protection: true
    realms:
      - Username-Password-Authentication
connections:
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients:
      - Default App
      - DeployCLI
      - SampleApp
    is_domain_connection: false
    options:
      email: true
      scope:
        - email
        - profile
      profile: true
tenant:
  enabled_locales:
    - en
  flags:
    universal_login: true
    revoke_refresh_token_grant: false
    dashboard_new_onboarding: false
    disable_clickjack_protection_headers: false
  sandbox_version: '16'
emailProvider:
  name: sendgrid
  credentials:
    api_key: '##SENDGRID_API_KEY##'
  default_from_address: gapa@q4magic.com
  enabled: true
emailTemplates:
  - template: enrollment_email
    body: ./emailTemplates/enrollment_email.html
    enabled: true
    from: ''
    subject: ''
    syntax: liquid
  - template: reset_email
    body: ./emailTemplates/reset_email.html
    enabled: true
    from: gapa@q4magic.com
    subject: Change password request
    syntax: liquid
    urlLifetimeInSeconds: 432000
  - template: verify_email
    body: ./emailTemplates/verify_email.html
    enabled: true
    from: gapa@q4magic.com
    resultUrl: http://localhost:3001
    subject: tesr veriry email....
    syntax: liquid
    urlLifetimeInSeconds: 432000
  - template: welcome_email
    body: ./emailTemplates/welcome_email.html
    enabled: true
    from: ''
    subject: ''
    syntax: liquid
clientGrants: []
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: recovery-code
    enabled: false
  - name: sms
    enabled: false
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: auth0
guardianPhoneFactorMessageTypes:
  message_types: []
roles: []
branding:
  templates: []
prompts:
  customText: {}
  universal_login_experience: new
migrations: {}
actions: []
triggers: {}
organizations: []
attackProtection:
  breachedPasswordDetection:
    enabled: false
    shields: []
    admin_notification_frequency: []
    method: standard
    stage:
      pre-user-registration:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams: []
themes:
  - borders:
      button_border_weight: 1
      buttons_style: rounded
      button_border_radius: 3
      input_border_weight: 1
      inputs_style: rounded
      input_border_radius: 3
      widget_corner_radius: 5
      widget_border_weight: 0
      show_widget_shadow: true
    colors:
      primary_button: '#2BB3E2'
      primary_button_label: '#ffffff'
      secondary_button_border: '#c9cace'
      secondary_button_label: '#1e212a'
      base_focus_color: '#2BB3E2'
      base_hover_color: '#000000'
      links_focused_components: '#2BB3E2'
      header: '#1e212a'
      body_text: '#1e212a'
      widget_background: '#ffffff'
      widget_border: '#c9cace'
      input_labels_placeholders: '#65676e'
      input_filled_text: '#000000'
      input_border: '#c9cace'
      input_background: '#ffffff'
      icons: '#65676e'
      error: '#d03c38'
      success: '#13a688'
    displayName: Unnamed Theme
    fonts:
      font_url: ''
      reference_text_size: 16
      title:
        bold: false
        size: 150
      subtitle:
        bold: false
        size: 87.5
      body_text:
        bold: false
        size: 87.5
      buttons_text:
        bold: false
        size: 100
      input_labels:
        bold: false
        size: 100
      links:
        bold: true
        size: 87.5
      links_style: normal
    page_background:
      page_layout: center
      background_color: '#000000'
      background_image_url: >-
        https://azr47-us-authx-ui-devlocal.azurewebsites.net/03781782-2c30-4e75-b72e-9afb59c17d4d/BackgroundImage/oscar-keys-medium.jpg
    widget:
      logo_position: center
      logo_url: >-
        https://azr47-us-authx-ui-devlocal.azurewebsites.net/03781782-2c30-4e75-b72e-9afb59c17d4d/Logo/umg-logo%402x.png
      logo_height: 52
      header_text_alignment: center
      social_buttons_layout: bottom


