name: Deploy to Auth0 Tenant2 account
on:
  push:
    paths: 
      - '**/tenant2/login.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install the auth0-deploy-cli
        run: npm install -g auth0-deploy-cli
      - name: Import changes to the Auth0 staging account
        run: npm run import:dev-tenant2